AWSTemplateFormatVersion: 2010-09-09
Description: Opensearch Tutorial


Parameters:
  Stage:
    Type: String
    Description: Stage of production
  AppName:
    Type: String
  MoviesMasterUserName:
    Type: String
    Default: admin
  MoviesMasterUserPassword:
    Type: String
    Default: Pa55word!
    NoEcho: true

Resources:
  OpenSearchKey:
    Type: 'AWS::KMS::Key'
    Properties:
      Description: OpenSearch tutorial key
      EnableKeyRotation: false
      KeyPolicy:
        Version: 2012-10-17
        Id: key-default-1
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: KMSKeyAdmin
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:user/Glindsey'
            Action:
              - 'kms:Create*'
              - 'kms:Describe*'
              - 'kms:Enable*'
              - 'kms:List*'
              - 'kms:Put*'
              - 'kms:Update*'
              - 'kms:Revoke*'
              - 'kms:Disable*'
              - 'kms:Get*'
              - 'kms:Delete*'
              - 'kms:ScheduleKeyDeletion'
              - 'kms:CancelKeyDeletion'
            Resource: '*'

  OpenSearchServiceDomain:
    Type: 'AWS::OpenSearchService::Domain'
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      DomainName: !Sub '${AppName}-movies'
      EngineVersion: 'OpenSearch_1.0'
      ClusterConfig:
        InstanceCount: '1'
        InstanceType: 't3.small.search'
      EBSOptions:
        EBSEnabled: true
        Iops: '0'
        VolumeSize: '10'
        VolumeType: 'gp2'
      AdvancedSecurityOptions:
        Enabled: true
        InternalUserDatabaseEnabled: true
        MasterUserOptions:
          MasterUserName: !Ref MoviesMasterUserName
          MasterUserPassword: !Ref MoviesMasterUserPassword
      NodeToNodeEncryptionOptions:
        Enabled: true
      EncryptionAtRestOptions:
        Enabled: true
        KmsKeyId: !GetAtt OpenSearchKey.Arn
      DomainEndpointOptions:
        EnforceHTTPS: true
      AccessPolicies: # required for open access using fine-grained access
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              AWS: '*'
            Action: 'es:*'
            Resource: !Sub 'arn:${AWS::Partition}:es:${AWS::Region}:${AWS::AccountId}:domain/${AppName}-movies/*'
      #   Version: '2012-10-17'
      #   Statement:
      #     - Effect: 'Allow'
      #       Principal:
      #         AWS: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:user/Glindsey'
      #       Action: 'es:*'
      #       Resource: !Sub 'arn:${AWS::Partition}:es:${AWS::Region}:${AWS::AccountId}:domain/test/*'
      # LogPublishingOptions:
      #   ES_APPLICATION_LOGS:
      #       CloudWatchLogsLogGroupArn: !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/opensearch/domains/opensearch-application-logs'
      #       Enabled: true
      #   SEARCH_SLOW_LOGS:
      #       CloudWatchLogsLogGroupArn: !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/opensearch/domains/opensearch-slow-logs'
      #       Enabled: true
      #   INDEX_SLOW_LOGS:
      #       CloudWatchLogsLogGroupArn: !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/opensearch/domains/opensearch-index-slow-logs'
      #       Enabled: true
      AdvancedOptions:
        rest.action.multi.allow_explicit_index: true
        override_main_response_version: true

# {
#   "Version": "2012-10-17",
#   "Statement": [
#     {
#       "Effect": "Allow",
#       "Principal": {
#         "AWS": "*"
#       },
#       "Action": "es:*",
#       "Resource": "arn:aws:es:us-east-1:763675941034:domain/opensearch-tutorial-movies/*"
#     }
#   ]
# }